#!/usr/bin/env bash
# Create a Docker VM, including Swarm multi-host networked VMs.

# Set values
pkg=${0##*/}

# set colors
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
purple=$(tput setaf 5)
cyan=$(tput setaf 6)
white=$(tput setaf 7)
reset=$(tput sgr0)

machine-init() {
  # Build test VM if needed
  DOCKER_MACHINE_NAME=${DOCKER_MACHINE_NAME:-"citest"} ; export DOCKER_MACHINE_NAME
  VBOX_DISK_SIZE=${VBOX_DISK_SIZE:-"10240"} ; export VBOX_DISK_SIZE

  docker-machine ls --quiet | grep "${DOCKER_MACHINE_NAME}" &>/dev/null
  if [ $? -ne 0 ]; then
    if [ ! -z ${create_machine} ]; then
      echo "${red}Docker host (${DOCKER_MACHINE_NAME}) does not exist and auto-creation disabled. Exiting.${reset}"
      exit 2
    fi
    echo "${yellow}Creating Docker host (${DOCKER_MACHINE_NAME})...${reset}"
    if [ -z $DOCKER_MACHINE_NODES ] || [ $DOCKER_MACHINE_NODES -lt 2 ]; then
      docker-machine create --driver virtualbox --virtualbox-disk-size ${VBOX_DISK_SIZE} ${DOCKER_MACHINE_NAME}
    else
      # Provision Swarm Manager and get token
      echo "${yellow}Creating Docker Swarm Manager (${DOCKER_MACHINE_NAME}-mgr)...${reset}"
      docker-machine create --driver virtualbox ${DOCKER_MACHINE_NAME}-mgr
      SWARM_MGR_ADDR=$(docker-machine ip ${DOCKER_MACHINE_NAME}-mgr) ; export SWARM_MGR_ADDR
      docker-machine ssh ${DOCKER_MACHINE_NAME}-mgr "docker swarm init --advertise-addr ${SWARM_MGR_ADDR}" &>/dev/null
      SWARM_MGR_TOKEN=$(docker-machine ssh ${DOCKER_MACHINE_NAME}-mgr "docker swarm join-token worker --quiet") ; export SWARM_MGR_TOKEN

      # Create Swarm Worker nodes
      for ((i=1; i<=${DOCKER_MACHINE_NODES}; i++)); do
        echo "${yellow}Creating Docker Swarm node (${DOCKER_MACHINE_NAME}-${i})...${reset}"
        docker-machine create --driver virtualbox \
          --virtualbox-disk-size ${VBOX_DISK_SIZE} \
          ${DOCKER_MACHINE_NAME}-${i}
        echo ${SWARM_MGR_TOKEN}
        docker-machine ssh ${DOCKER_MACHINE_NAME}-${i} "docker swarm join --token ${SWARM_MGR_TOKEN} ${SWARM_MGR_ADDR}:2377"
      done

      # Create overlay network
      echo "${yellow}Creating Docker Overlay multi-host network (${DOCKER_MACHINE_NAME}-net)...${reset}"
      docker-machine ssh ${DOCKER_MACHINE_NAME}-mgr "docker network create --driver overlay --subnet 172.16.0.0/28 ${DOCKER_MACHINE_NAME}-net"
    fi
  else
    docker-machine ls | grep ${DOCKER_MACHINE_NAME} | grep Running &>/dev/null
    if [ $? -ne 0 ]; then
      echo "${green}Starting Docker host (${DOCKER_MACHINE_NAME})...${reset}"
      docker-machine start ${DOCKER_MACHINE_NAME}
    fi
  fi
}

cleanup() {
  unset SWARM_MGR_ADDR
  unset SWARM_MGR_TOKEN
  unset VBOX_DISK_SIZE
}
usage() {
cat <<EOM

$pkg

Create Docker VM.

Usage: $pkg [OPTIONS]

Options:
  -h,--help               Output help (this message)
  -nc,--no-create         Do not create Docker VM host
  -m=,--machine=[NAME]    Use specified name for Docker VM host (default 'citest')
  -n=,--nodes=[#]         Create specified number of nodes in multi-host configuration.
                          Hosts names will be in the format '[machine name]-#'
  -s=,--size=[MB]         Use specified value in MB for Docker VM storage (defaults to 10240)

EOM
}

# Process command line
for arg in "$@"; do
  if test -n "$prev_arg"; then
    eval "$prev_arg=\$arg"
    prev_arg=
  fi

  case "$arg" in
      -*=*) optarg=`echo "$arg" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
      *) optarg= ;;
  esac

  case $arg in
    -h | --help)
      usage && exit 0
      ;;
    -nc | --no-create)
      create_machine=0
      ;;
    -m=* | --machine=*)
      DOCKER_MACHINE_NAME="$optarg"
      ;;
    -n=* | --nodes=*)
      DOCKER_MACHINE_NODES="$optarg"
      ;;
    -s=* | --size=*)
      VBOX_DISK_SIZE="$optarg"
      ;;
    -*)
      echo "${red}Unknown option $arg, exiting...${reset}" && exit 1
      ;;
    *)
      echo "${red}Unknown option or missing argument for $arg, exiting.${reset}"
      usage
      exit 1
      ;;
  esac
done

machine-init
cleanup
