#!/bin/bash

# set colors
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
purple=$(tput setaf 5)
cyan=$(tput setaf 6)
white=$(tput setaf 7)
reset=$(tput sgr0)

echo -e "${green}Deploying updates to GitHub...${reset}"

# Build the project.
mkdocs gh-deploy --clean