#!/bin/bash
# SSH auto completer

_ssh ()
{
  local cur hosts
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  hosts=$(cat ~/.ssh/config ~/.ssh/conf.d/*.ssh | \
                  grep "^Host " | grep -v '\*' | uniq | \
                  awk '{print $2}')
  COMPREPLY=( $(compgen -W "${hosts}" -- ${cur}))
  return 0
}
complete -F _ssh ssh
