#!/bin/bash
# SSH auto completer

_ssh ()
{
  local cur prev hosts
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  hosts=$(grep '^Host' ~/.ssh/config ~/.ssh/conf.d/*.ssh 2>/dev/null | \
                  grep -v '\*' | uniq | \
                  awk '{print $2}')
  COMPREPLY=( $(compgen -W "${hosts}" -- ${cur}))
  return 0
}
complete -F _ssh ssh
