#!/bin/bash
# Update all ruby gems and bundles

for ver in $(rbenv versions --bare); do
  RBENV_VERSION=${ver}
  ruby --version
  gem update --system --no-rdoc --no-ri
  gem update --no-rdoc --no-ri
done
