#!/bin/bash
# Update all pip installations

##pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs sudo -H pip install -U
pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs pip install -U